url: "https://nasiijau.github.io/gallery/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/gallery" # the subpath of your site, e.g. /blog
title: "nas" # the name of your site, e.g. ACME Corp.
